config/routes.rb
Rails.application.routes.draw do
  
  resources :apparatus
  devise_for :personnels,:path => "personnel", :controllers => { registrations: 'registrations' }
  resources :personnels, :path => "personnel", only: [:index, :edit, :update, :show, :destroy]
  

  root 'pages#index'
  
  resources :qualifications
  resources :personnel_qualifications, except: [:show, :edit, :update]
  resources :rosters, :path => "roster"
  resources :positions
  resources :assignments, only: [:index, :create, :update, :destroy]
  
  get 'send_mail/:id', to: 'rosters#send_mail', as: :send_mail

end

app/models/roster.rb
class Roster < ActiveRecord::Base
  has_many :roster_apparatus
  has_many :apparatus, through: :roster_apparatus
  has_many :assignments, dependent: :destroy
  before_save :downcase_name
  validates :name, presence: true
  validates :start_time, presence: true, uniqueness: true
  validates :end_time, presence: true, uniqueness: true
  
  def downcase_name
    self.name.downcase!
  end
    
end

app/controllers/rosters_controller.rb
class RostersController < ApplicationController
  before_action :authenticate_personnel!, except: [:show]
  before_action :set_roster, only: [:show, :edit, :update, :send_email, :destroy]
  before_action :is_admin?, only: [:create, :new, :edit, :destroy]

  # GET /rosters
  # GET /rosters.json
  def index
    @rosters = Roster.all
  end

  # GET /rosters/1
  # GET /rosters/1.json
  def show
    @roster = Roster.find(params[:id])
    @positions = @roster.apparatus.collect{|a| a.positions}.flatten.uniq
    @assignment = @roster.assignments.find{|a| a.roster_id == @roster.id }
    #@assign = @assignment.id
  end

  # GET /rosters/new
  def new
    @roster = Roster.new
    @apparatus = Apparatu.all
  end

  # GET /rosters/1/edit
  def edit
    @apparatus = Apparatu.all
  end

  # POST /rosters
  # POST /rosters.json
  def create
    @roster = Roster.new(roster_params)
    @roster.name = "week of #{@roster.start_time.strftime("%m/%d/%Y")}"
    @roster.end_time = @roster.start_time.end_of_week

    respond_to do |format|
      if @roster.save
        format.html { redirect_to @roster, notice: 'Roster was successfully created.' }
        format.json { render :show, status: :created, location: @roster }
      else
        format.html { render :new }
        format.json { render json: @roster.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rosters/1
  # PATCH/PUT /rosters/1.json
  def update
    respond_to do |format|
      if @roster.update(roster_params)
        format.html { redirect_to @roster, notice: 'Roster was successfully updated.' }
        format.json { render :show, status: :ok, location: @roster }
      else
        format.html { render :edit }
        format.json { render json: @roster.errors, status: :unprocessable_entity }
      end
    end
  end
  
  #def send_order_mail
    #@order = Order.find(params[:id])
    #@client = Customer.find(@order.client_id)
  
    #OrderMailer.order_send(@order, @client).deliver
    #flash[:notice] = "Order has been sent."
    #redirect_to order_path(@order.id)
  #end
  
  def send_mail
    @roster = Roster.find(params[:id])
    #@deploy = @roster.assignments.where(alternate: false)
    @personnel = Personnel.all
    DeploymentNotifier.send_deployment_roster(@roster, @personnel).deliver
    flash[:notice] = "Deployment email has been sent."
    redirect_to @roster
  end

  # DELETE /rosters/1
  # DELETE /rosters/1.json
  def destroy
    @roster.destroy
    respond_to do |format|
      format.html { redirect_to rosters_url, notice: 'Roster was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_roster
      @roster = Roster.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def roster_params
      params.require(:roster).permit(:name, :start_time, :end_time, apparatu_ids:[])
    end
end

app/helpers/rosters_helper.rb
module RostersHelper
  
  def deployment_email_helper(roster, app)
    @apparatus = app
    @deploy = @roster.assignments.where(alternate: false, apparatu_id: @apparatus)
    @can_deploy = @deploy.where(deploy: false)
    if !@can_deploy.any? && @roster.assignments.any?
      link_to 'Send Deployment Email', send_mail_path, id: @roster.id, class: 'btn btn-success'
    end
  end
  
end

app/views/rosters/_form.html.erb
  <% if @roster.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@roster.errors.count, "error") %> prohibited this roster from being saved:</h2>

      <ul>
      <% @roster.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="row">
  <div class="col-md-6">
    <%= form_for(@roster, :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <% if current_personnel && current_personnel.admin? %>
      
        <% if @roster.name %>
          <div class="form-group">
            <div class="form-group">
              <%= f.label :name, class: "col-sm-4 control-label" %>
              <div class="col-sm-6">
                <%= f.text_field :name, value: @roster.name.capitalize, class: "form-control", readonly: true %>
              </div>
            </div>  
          </div>
        <% end %>
        <!--<div class="form-group">
          <%#= f.label :name, class: "col-sm-4 control-label" %>
          <div class="col-sm-4">
            <%#= f.text_field :name, autofocus: true, class: "form-control" %>
          </div>
        </div>-->
        <div class="form-group">
          <%= f.label :start_time, class: "col-sm-4 control-label" %>
          <div class="col-sm-8" style="position: relative; z-index: 100000;">
            <%= f.text_field :start_time, "data-provide" => 'datepicker', class: "form-control", id: "start_time" %>
          </div>
        </div>
        <!--<div class="form-group">
          <%#= f.label :end_time, class: "col-sm-4 control-label" %>
          <div class="col-sm-8" style="position: relative; z-index: 100000;">
            <%#= f.date_select :end_time, class: "form-control" %>
            <%#= f.text_field :end_time, "data-provide" => 'datepicker', class: "form-control", id: "end_time" %>
          </div>
        </div>-->
        
        <%= fields_for(@roster, @roster.roster_apparatus.build) do |a| %>
          <div class="form-group">
            <%= a.label :apparatus, class: "col-sm-4 control-label" %>
            <div class="collection-check-box col-sm-8">
              <%= a.collection_check_boxes :apparatu_ids, Apparatu.all, :id, :designator do |b| %>
                
                  <%= b.check_box %>
                  <%= b.label %>
                
              <% end %> 
            </div>  
          </div>
        <% end %>
        
      <% end %>  
      <div class="col-sm-4 col-sm-offset-4">
        <%= f.submit 'Submit Roster', class: "btn btn-xs btn-primary" %> | 
        <%= link_to 'Back', rosters_path %>
      </div>
    <% end %>
  </div>
</div>  

app/views/rosters/edit.html.erb
<h1>Editing Roster</h1>

<%= render 'form' %>

app/views/rosters/index.html.erb
<%= month_calendar events: @rosters do |date, rosters| %>
  <%= date.strftime("%d") %>

  <% rosters.each do |roster| %>
    <div>
      <strong><%= link_to roster.name.titleize, roster_path(roster) %></strong>
    </div>
  <% end %>
<% end %>

<!--<p id="notice"><%#= notice %></p>-->

<h1 class="roster-h1">Current Rosters</h1>

<table class="table table-striped roster-table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Start Date</th>
      <th>End Date</th>
      <th>Apparatus</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @rosters.each do |roster| %>
      <% if roster.start_time >= Date.today.beginning_of_week %>
        <tr>
          <td><%= roster.name.titleize %></td>
          <td><%= roster.start_time.strftime("%m/%d/%Y") %></td>
          <td><%= roster.end_time.strftime("%m/%d/%Y") %></td>
          <td>
            <% if roster.apparatus.size > 0 %>
              <% roster.apparatus.each do |app| %>
                <%= app.designator.upcase %>
              <% end %>  
            <% end %>
          </td>
          <td>
            <%= link_to 'View', roster, class: "btn btn-xs btn-primary" %>                     
            <% if current_personnel.admin? %> 
              <%= link_to 'Edit', edit_roster_path(roster), 
                                  class: "btn btn-xs btn-success" %>
              <%= link_to 'Destroy', roster, method: :delete, 
                                  class: "btn btn-xs btn-danger", 
                                  data: { 
                                    confirm: "Are you sure you want to delete the roster: #{roster.name.titleize}?" 
                                  } %>
            <% end %>                      
          </td>
        </tr>
      <% end %>  
    <% end %>
  </tbody>
</table>

<% if current_personnel.admin? %>
  <%= link_to 'New Roster', new_roster_path, class: "btn btn-xs btn-primary" %>
<% end %>  

app/views/rosters/new.html.erb
<h1>New Roster</h1>

<%= render 'form' %>

app/views/rosters/show.html.erb
<h2>
  <%= @roster.name.titleize %> 
</h2>
<h5>
  Roster Dates <%= @roster.start_time.strftime("%m/%d/%Y") %> - <%= @roster.end_time.strftime("%m/%d/%Y") %>
</h5>

<% if @roster.apparatus.size > 0 %>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Apparatus</th>
        <% @positions.sort.each do |pos| %>
          <th><%= pos.name.titleize %></th>
        <% end %>
      </tr>
    </thead>
    <tbody>
      <% @roster.apparatus.each do |app| %>
      <tr>
        <td><%= app.designator.upcase %></td>
              
        <% @positions.sort.each do |poss| %>
          <td>
            
              <% if assignment = @roster.assignments.find{|a| a.position_id == poss.id && a.apparatu_id == app.id} %>
                <strong><%= assignment.personnel.full_name.titleize %></strong>
                <% if current_personnel.try(:admin?) %>
                  <%= link_to 'Remove', assignment_path(assignment), method: :delete, 
                                        class: "btn btn-xs btn-danger",
                                        data: { confirm: "Remove #{assignment.personnel.full_name.titleize}?" } %>
                <% end %>
              <% elsif unfilled_pos = app.positions.find{|p| p.id == poss.id}%>
                <% if current_personnel && current_personnel.can_signup?(@roster.id) && current_personnel.is_qualified?(unfilled_pos) %>
                  <div class="signup-action" data-apparatu-id="<%= app.id %>" data-position-id="<%= unfilled_pos.id %>">
                    <%#= link_to 'Signup', assignments_path(roster_id: @roster.id, position_id: unfilled_pos.id, apparatu_id: app.id), class: "btn btn-xs btn-primary" %>
                  
                    <%= form_for Assignment.new do |f| %>
                      <%= f.hidden_field :roster_id, value: @roster.id %>
                      <%= f.hidden_field :position_id, value: unfilled_pos.id %>
                      <%= f.hidden_field :apparatu_id, value: app.id %>
                      <%= f.hidden_field :personnel_id, value: current_personnel.id %><!-- add this to not use create.js -->
                      <%= f.submit 'Signup', class: "btn btn-xs btn-primary" %>
                    <% end %>
                  </div>
                  
                <!-- Modal for manually signing up personnel -->  
                <% elsif current_personnel.try(:admin?) %>
                  <%#= link_to 'Add Person', '#', class: "btn btn-xs btn-primary" %>
                  
                  <!-- Button trigger modal -->
                  <button type="button" class="btn btn-primary btn-xs" data-toggle="modal" data-target="#myModal<%= unfilled_pos.id %>">
                    Add Person
                  </button>
                  
                  <!-- Modal -->
                  <div class="modal fade" id="myModal<%= unfilled_pos.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                    <div class="modal-dialog" role="document">
                      <div class="modal-content">
                        <div class="modal-header">
                          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                          <h4 class="modal-title" id="myModalLabel">Add Person to Roster</h4>
                        </div>
                        <div class="modal-body">
                          
                          <%= form_for Assignment.new do |f| %>
                            <%= f.hidden_field :roster_id, value: @roster.id %>
                            <%= f.hidden_field :position_id, value: unfilled_pos.id %>
                            <%= f.hidden_field :apparatu_id, value: app.id %>
                            <% Personnel.all.each do |p| %>
                              <% if p.can_signup?(@roster.id) && p.is_qualified?(unfilled_pos) %>
                                <p>
                                  <%= f.radio_button :personnel_id, p.id %>
                                  <%= f.label :personnel_id, p.full_name.titleize %>
                                </p>
                              <% end %>  
                            <% end %>
                            
                            <%#= collection_radio_buttons(:assignment, :personnel_id, Personnel.all, :id, :full_name) do |b| %>
                              <!--<p><%#= b.label(:"data-value" => b.value) { b.radio_button + b.text.titleize } %></p>-->
                            <%# end %>  
                            <%= f.submit 'Add Person', class: "btn btn-xs btn-primary" %>
                          <% end %>
                          
                        </div>
                      </div>
                    </div>
                  </div>
                  
                  
                <% elsif current_personnel && current_personnel.can_signup?(@roster.id) %>
                  <em>Not Qualified</em>
                <% else %>
                  <em>Need Personnel</em>
                  <%# if current_personnel.try(:admin?) %>
                    <%#= link_to 'Add Person', '#', class: "btn btn-xs btn-primary" %>
                  <%# else %>
                    <!--<em>Need Personnel</em>-->
                  <%# end %>  
                <% end %>
              <% else %>
                <i class="fa fa-user-times" aria-hidden="true"></i>
              <% end %> 
            
          </td>
        <% end %>
              
      </tr> 
    <% end %> 
    </tbody>
  </table> 
<% end %> 

<p class="notes">
  <i class="fa fa-user-times" aria-hidden="true"></i> = Position not required
</p> 

<p class="notes text-center">
  <strong>
    <i class="fa fa-asterisk" aria-hidden="true"></i> Remember you must be
    available for at least 16 days from the last day of the Roster 
    <i class="fa fa-asterisk" aria-hidden="true"></i>
  </strong>
</p>

<p class="links">
  <% if current_personnel && current_personnel.admin? %>
    <%= link_to 'Edit', edit_roster_path(@roster), class: "btn btn-xs btn-primary" %> | 
    <%= link_to 'Back', rosters_path, class: "no-bg" %>
  <% elsif current_personnel %>
    <%= link_to 'Back', rosters_path, class: "no-bg" %>
  <% else %>
    <%= link_to 'Back', root_path, class: "no-bg" %>
  <% end %> 
</p>

<% if current_personnel && current_personnel.can_signup?(@roster.id) %>  
  <p>
    <%= form_for Assignment.new do |f| %>
      <%= f.hidden_field :roster_id, value: @roster.id %>
      <%= f.hidden_field :personnel_id, value: current_personnel.id %>
      <%= f.hidden_field :alternate, value: true %>
      <%= f.submit 'Signup As Alternate', class: "btn btn-sm btn-success" %>
    <% end %>
  </p>
<% end %> 

<div class="alternates">
  <h3>Alternates</h3>
  <% @roster.assignments.order("created_at asc").each do |assign| %>
    <% if assign.alternate? %>
      <div class="row">
        <div class="col-md-4">
          <p>
            <%= link_to assign.personnel.full_name.titleize,
            personnel_path(assign.personnel.id), class: "back-btn" %>
            <span>
              <%= number_to_phone(assign.personnel.phone, area_code: true) %>
            </span>
            <span>
              <% assign.personnel.qualifications.each do |qual| %>
                <strong><%= qual.acronym.upcase %></strong>
              <% end %>
            </span>
          </p>
        </div>
        <% if current_personnel == assign.personnel || current_personnel.try(:admin?) %>
          <div class="col-md-2">
            <p>
              <%= link_to 'Remove to add to Roster', assignment_path(assign), method: :delete, 
                                            class: "btn btn-xs btn-danger",
                                            data: { confirm: "Remove #{assign.personnel.full_name.titleize}?" } %>
            </p>                                
          </div>
        <% end %>  
      </div>  
    <% end %>
  <% end %>
</div>  

<hr>

<% if @roster.apparatus.size > 0 %>
  <div class="roster-list">
    <h3>Personnel Contact Info</h3>
    <% @roster.apparatus.each do |app| %>
      <div class="col-md-12 roster-list-personnel">
        <h4><%= app.name.titleize %></h4>
          <% @positions.sort.each do |poss| %>
            <% if @assign = @roster.assignments.find{|a| a.position_id == poss.id && a.apparatu_id == app.id} %> 
              <div class="row">
                <div class="col-md-2">
                  <p class="pos"><%= @assign.position.name.titleize %></p> 
                </div>
                <div class="col-md-4 text-left">
                  <p>
                    <%= link_to @assign.personnel.full_name.titleize, personnel_path(@assign.personnel.id), class: "back-btn" %> 
                    <span>
                      <%= number_to_phone(@assign.personnel.phone, area_code: true) %>
                    </span>
                    <span>
                      <% if current_personnel.try(:admin?) %>
                        <% if !@assign.deploy? %>
                        
                          <%#= form_for @assignment do |f| %>
                            <%#= f.hidden_field :deploy, value: true %>
                            <%#= f.submit 'Deploy', class: "btn btn-xs btn-success" %>
                          <%# end %>
                          
                          <%#= @assign.id %>
                      
                          <%= link_to "Deploy", assignment_path(@assign, deploy: true), method: :put, class: "btn btn-xs btn-success" %>
                        <% else %> 
                          <%= link_to "Undo Deploy", assignment_path(@assign, deploy: false), method: :put, class: "btn btn-xs btn-warning" %>
                        <% end %>  
                      <% else %>
                        <% if @assign.deploy %>
                          <strong style="color: #FF0000;"><emd>Deployed</emd></strong>
                        <% end %>
                      <% end %>
                      
                    </span>
                  </p>
                </div>
              </div>  
            <% end %> 
          <% end %>
          <% if current_personnel.try(:admin?) %>
            <%= deployment_email_helper(@roster, app) %>
          <% end %> 
      </div>
    <% end %>
  </div>
  
   
  
<% end %>