config/routes.rb
Rails.application.routes.draw do
  
  resources :apparatus
  devise_for :personnels,:path => "personnel", :controllers => { registrations: 'registrations' }
  resources :personnels, :path => "personnel", only: [:index, :edit, :update, :show, :destroy]
  

  root 'pages#index'
  
  resources :qualifications
  resources :personnel_qualifications, except: [:show, :edit, :update]
  resources :rosters, :path => "roster"
  resources :positions
  resources :assignments, only: [:index, :create, :update, :destroy]
  
  get 'send_mail/:id', to: 'rosters#send_mail', as: :send_mail

end

app/models/qualification.rb
class Qualification < ActiveRecord::Base
    has_many :personnel_qualifications
    has_many :personnels, through: :personnel_qualifications
    validates :name, presence: true, uniqueness: true
    validates :acronym, presence: true, uniqueness: true
    before_save :downcase_name, :downcase_acronym
    
    def downcase_name
      self.name.downcase!
    end
    
    def downcase_acronym
      self.acronym.downcase!
    end
    
    #def name
    #  self[:name].titleize
    #end
    
end

app/controllers/qualifications_controller.rb
class QualificationsController < ApplicationController
    before_action :is_admin?
    
    def index
        @qualifications = Qualification.all
    end
    
    def new
        @qualification = Qualification.new
    end
    
    def create
        @qualification = Qualification.new(qual_params)
        if @qualification.save
            flash[:notice] = "Qual was created"
            redirect_to qualifications_path
        else
            render 'new'
        end
    end
    
    def edit
    
    end
    
    def update
    end
    
    def destroy
        @qualification = Qualification.find(params[:id])
        @qualification.destroy
        flash[:notice] = "#{@qualification.name} was deleted"
        redirect_to qualifications_path
    end
    
    private
    
        def qual_params
           params.require(:qualification).permit(:name, :acronym) 
        end


end

app/views/qualifications/index.html.erb
<% if @qualifications.size > 0 %>
    <h1>Qualifications <%= link_to "New Qual", new_qualification_path, class: "btn btn-s btn-primary" %></h1>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Name</th>
                <th>Abbr.</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            <% @qualifications.order(:name).each do |qual| %>
                <tr>
                    <td><%= qual.name.titleize %></td>
                    <td><%= qual.acronym.upcase %></td>
                    <td>
                        <% if current_personnel.admin? %>
                            <%= link_to 'Delete', qualification_path(qual), 
                                        :method => :delete, 
                                        :data => { :confirm => "Are you sure you want to delete #{qual.name}?" }, 
                                        :class => "btn btn-xs btn-danger" %>
                        <% end %>                        
                    </td>
                        
                </tr>
            <% end %>
        </tbody>
    </table>
<% end %>

app/views/qualifications/new.html.erb
<h1>Create a new qual</h1>

<div class="row">
<% if @qualification.errors.any? %>
    <div class="col-md-4 alert alert-danger">
        <ul>
            <% @qualification.errors.full_messages.each do | msg | %>
                <li><%= msg %></li>
            <% end %>
        </ul>
    </div>
<% end %>
</div>
<div class="row">
<div class="col-md-6">
    <%= form_for(@qualification, :html => {class: "form-horizontal", role: "form"}) do |f| %>
        <div class="form-group">
            <%= f.label :name, class: "col-sm-2 control-label" %>
            <div class="col-sm-4">
                <%= f.text_field :name, :placeholder => "engine boss", autofocus: "true", class: "form-control" %>
            </div>    
        </div>
        <div class="form-group">
            <%= f.label :acronym, class: "col-sm-2 control-label" %>
            <div class="col-sm-4">
                <%= f.text_field :acronym, :placeholder => "engb", class: "form-control" %>
            </div>    
        </div>
        <div class="col-sm-4 col-md-offset-2">
            <%= f.submit 'Create', class: "btn btn-xs btn-primary" %> 
            <%= link_to 'Cancel', qualifications_path, 
                                class: "btn btn-xs btn-danger custom-btn",
                                style: "margin-left:15px" %>
        </div>    
    <% end %> 
</div> 
</div>