config/routes.rb
Rails.application.routes.draw do
  
  resources :apparatus
  devise_for :personnels,:path => "personnel", :controllers => { registrations: 'registrations' }
  resources :personnels, :path => "personnel", only: [:index, :edit, :update, :show, :destroy]
  

  root 'pages#index'
  
  resources :qualifications
  resources :personnel_qualifications, except: [:show, :edit, :update]
  resources :rosters, :path => "roster"
  resources :positions
  resources :assignments, only: [:index, :create, :update, :destroy]
  
  get 'send_mail/:id', to: 'rosters#send_mail', as: :send_mail

end

app/models/personnel_qualification.rb
class PersonnelQualification < ActiveRecord::Base
    belongs_to :personnel
    belongs_to :qualification
    
end

app/controllers/personnel_qualifications_controller.rb
class PersonnelQualificationsController < ApplicationController
  before_action :set_personnel_qualification, only: [:show, :edit, :update, :destroy]

  # GET /personnel_qualifications
  # GET /personnel_qualifications.json
  def index
    @personnel_qualifications = PersonnelQualification.all
  end

  # GET /personnel_qualifications/1
  # GET /personnel_qualifications/1.json
  def show
  end

  # GET /personnel_qualifications/new
  def new
    @personnel_qualification = PersonnelQualification.new
  end

  # GET /personnel_qualifications/1/edit
  def edit
  end

  # POST /personnel_qualifications
  # POST /personnel_qualifications.json
  def create
    @personnel_qualification = PersonnelQualification.new(qualification_id: params[:qualification_id], personnel_id: params[:personnel_id])

    respond_to do |format|
      if @personnel_qualification.save
        format.html { redirect_to personnels_path, notice: 'Personnel qualification was successfully created.' }
        format.json { render :show, status: :created, location: @personnel_qualification }
      else
        format.html { render :new }
        format.json { render json: @personnel_qualification.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /personnel_qualifications/1
  # PATCH/PUT /personnel_qualifications/1.json
  def update
    respond_to do |format|
      if @personnel_qualification.update(personnel_qualification_params)
        format.html { redirect_to @personnel_qualification, notice: 'Personnel qualification was successfully updated.' }
        format.json { render :show, status: :ok, location: @personnel_qualification }
      else
        format.html { render :edit }
        format.json { render json: @personnel_qualification.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /personnel_qualifications/1
  # DELETE /personnel_qualifications/1.json
  def destroy
    @personnel_qualification.destroy
    respond_to do |format|
      format.html { redirect_to personnel_qualifications_url, notice: 'Personnel qualification was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_personnel_qualification
      @personnel_qualification = PersonnelQualification.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def personnel_qualification_params
      params.require(:personnel_qualification).permit(:personnel_id, :qualification_id)
    end
end

app/helpers/personnel_qualifications_helper.rb
module PersonnelQualificationsHelper
end

app/views/personnel_qualifications/_form.html.erb
<%= form_for(@personnel_qualification) do |f| %>
  <% if @personnel_qualification.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@personnel_qualification.errors.count, "error") %> prohibited this personnel_qualification from being saved:</h2>

      <ul>
      <% @personnel_qualification.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :personnel_id %><br>
    <%= f.number_field :personnel_id %>
  </div>
  <div class="field">
    <%= f.label :qualification_id %><br>
    <%= f.number_field :qualification_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/personnel_qualifications/edit.html.erb
<h1>Editing Personnel Qualification</h1>

<%= render 'form' %>

<%= link_to 'Show', @personnel_qualification %> |
<%= link_to 'Back', personnel_qualifications_path %>

app/views/personnel_qualifications/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Personnel Qualifications</h1>

<table>
  <thead>
    <tr>
      <th>Personnel</th>
      <th>Qualification</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @personnel_qualifications.each do |personnel_qualification| %>
      <tr>
        <td><%= personnel_qualification.personnel_id %></td>
        <td><%= personnel_qualification.qualification_id %></td>
        <td><%= link_to 'Show', personnel_qualification %></td>
        <td><%= link_to 'Edit', edit_personnel_qualification_path(personnel_qualification) %></td>
        <td><%= link_to 'Destroy', personnel_qualification, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Personnel qualification', new_personnel_qualification_path %>

app/views/personnel_qualifications/new.html.erb
<h1>New Personnel Qualification</h1>

<%= render 'form' %>

<%= link_to 'Back', personnel_qualifications_path %>

app/views/personnel_qualifications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Personnel:</strong>
  <%= @personnel_qualification.personnel_id %>
</p>

<p>
  <strong>Qualification:</strong>
  <%= @personnel_qualification.qualification_id %>
</p>

<%= link_to 'Edit', edit_personnel_qualification_path(@personnel_qualification) %> |
<%= link_to 'Back', personnel_qualifications_path %>