config/routes.rb
Rails.application.routes.draw do
  
  resources :apparatus
  devise_for :personnels,:path => "personnel", :controllers => { registrations: 'registrations' }
  resources :personnels, :path => "personnel", only: [:index, :edit, :update, :show, :destroy]
  

  root 'pages#index'
  
  resources :qualifications
  resources :personnel_qualifications, except: [:show, :edit, :update]
  resources :rosters, :path => "roster"
  resources :positions
  resources :assignments, only: [:index, :create, :update, :destroy]
  
  get 'send_mail/:id', to: 'rosters#send_mail', as: :send_mail

end

app/views/layouts/_footer.html.erb
<footer>
  <p>&copy; Aurora Fire Rescue <%= Time.now.year %> ~ Aurora, Colorado</p>
</footer>

app/views/layouts/_header.html.erb
<div class="navbar navbar-default navbar-static-top">
  <div class="container">
    <button type="button" class="navbar-toggle" data-toggle="collapse" 
                          data-target=".navbar-responsive-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to(image_tag("AFR_Logo_Small.png", height: '100'), root_url, 
                                                class: "pull-left logo") %>
    <div class="navbar-collapse collapse navbar-responsive-collapse">
      <ul class="nav navbar-nav">
        <% if current_personnel %>
          <li><%= link_to "Personnel", personnels_path  %></li>
          <li><%= link_to "Roster", rosters_path  %></li>
        <% end %>  
        <% if current_personnel && current_personnel.admin? %>
          <li><%= link_to "Qualifications", qualifications_path  %></li>
          <li><%= link_to "Apparatus", apparatus_path %></li>
        <% end %>  
      </ul>
      
      <% if current_personnel %>
      <ul class="nav logout navbar-right navbar-btn">
        <li>
            <%= link_to "logout", destroy_personnel_session_path, 
                                  method: :delete,
                                  class: "btn btn-xs btn-danger" %>
        </li>
      </ul>
      <ul class="nav user-name navbar-right navbar-btn">
        <li>
          <i class="fa fa-user"> 
            <%= link_to current_personnel.full_name.titleize, 
                        personnel_path(current_personnel.id) %>
          </i>
          <%#= current_personnel.full_name.present? ? current_personnel.full_name.titleize : current_personnel.email %>
        </li>
      </ul>
      <% else %>
      <ul class="nav login navbar-right navbar-btn">
        <li>
            <%= link_to "Log In", new_personnel_session_path,
                                  class: "btn btn-xs btn-primary" %>
        </li>
      </ul>
      <ul class="nav signup navbar-right navbar-btn">
        <li>
            <%= link_to "Sign Up!", new_personnel_registration_path,
                                   class: "btn btn-xs" %>
        </li>
      </ul>
      <% end %>
      
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Aurora Fire Rescue Wildland Team" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', 
                          :rel => 'apple-touch-icon-precomposed', 
                          :type => 'image/png', 
                          :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', 
                          :rel => 'apple-touch-icon-precomposed', 
                          :type => 'image/png', 
                          :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', 
                          :rel => 'apple-touch-icon-precomposed', 
                          :type => 'image/png', 
                          :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', 
                          :rel => 'apple-touch-icon-precomposed', 
                          :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <%= render "layouts/header" %>

    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        
        <%#= debug(params) if Rails.env.development? %>
        <!--<div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3>Sidebar</h3>
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div>
        </div>
      </div>-->
    </div> <!-- /container -->  
    
    <%= render "layouts/footer" %>

  </body>
</html>